src/Entity/Anounce.php
<?php

namespace App\Entity;

use DateTime;
use App\Entity\User;
use Cocur\Slugify\Slugify;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\AnounceRepository;
use Doctrine\Common\Collections\Collection;
use Symfony\Component\HttpFoundation\File\File;
use Doctrine\Common\Collections\ArrayCollection;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
use Symfony\Component\Validator\Constraints as Assert;
use Vich\UploaderBundle\Mapping\Annotation\Uploadable;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Vich\UploaderBundle\Mapping\Annotation\UploadableField;

/**
 * @ORM\Entity(repositoryClass=AnounceRepository::class)
 * @ORM\Table(name="anounce", indexes={@ORM\Index(columns={"title", "desription"}, flags={"fulltext"})}) 
 * @ORM\HasLifecycleCallbacks()
 * @Vich\Uploadable
 */
class Anounce
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $slug;

    /**
     * @ORM\Column(type="text")
     * @Assert\NotBlank
     */
    private $desription;

    /**
     * @ORM\Column(type="float")
     * @Assert\NotBlank
     * @Assert\Type("float")
     */
    private $price;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $address;

    /**
     * NOTE: This is not a mapped field of entity metadata, just a simple property.
     * 
     * @Vich\UploadableField(mapping="cover_images", fileNameProperty="imageName")
     * 
     * @var File|null
     */
    private $coverImage;

    /**
     * @ORM\Column(type="string")
     *
     * @var string|null
     */
    private $imageName;

    /**
     * @ORM\Column(type="integer")
     * @Assert\NotBlank
     * @Assert\Type("integer")
     */
    private $rooms;

    /**
     * @ORM\Column(type="boolean")
     */
    private $isAvailable;

    /**
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    /**
     * @ORM\OneToMany(targetEntity=Comment::class, mappedBy="anounce", cascade={"persist", "remove"})
     */
    private $comments;

    /**
     * @ORM\OneToMany(targetEntity=Image::class, mappedBy="anounce", cascade={"persist", "remove"})
     */
    private $images;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $intro;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="anounces")
     */
    private $user;

    public function __construct()
    {
        $this->comments = new ArrayCollection();
        $this->images = new ArrayCollection();
    }

    /**
     * @ORM\PrePersist
     * @ORM\PreUpdate
     */
    public function initSlug()
    {
        $slugger = new Slugify();
        $this->slug = $slugger->slugify($this->title);
    }
    /**
     * @ORM\PrePersist
     * @ORM\PreUpdate
     */
    public function initCreatedAt()
    {
        $this->createdAt = new DateTime();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getDesription(): ?string
    {
        return $this->desription;
    }

    public function setDesription(string $desription): self
    {
        $this->desription = $desription;

        return $this;
    }

    public function getPrice(): ?float
    {
        return $this->price;
    }

    public function setPrice(float $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(string $address): self
    {
        $this->address = $address;

        return $this;
    }

    public function getRooms(): ?int
    {
        return $this->rooms;
    }

    public function setRooms(int $rooms): self
    {
        $this->rooms = $rooms;

        return $this;
    }

    public function getIsAvailable(): ?bool
    {
        return $this->isAvailable;
    }

    public function setIsAvailable(bool $isAvailable): self
    {
        $this->isAvailable = $isAvailable;

        return $this;
    }

    public function getCreatedAt(): ?\DateTime
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTime $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setAnounce($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getAnounce() === $this) {
                $comment->setAnounce(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Image[]
     */
    public function getImages(): Collection
    {
        return $this->images;
    }

    public function addImage(Image $image): self
    {
        if (!$this->images->contains($image)) {
            $this->images[] = $image;
            $image->setAnounce($this);
        }

        return $this;
    }

    public function removeImage(Image $image): self
    {
        if ($this->images->removeElement($image)) {
            // set the owning side to null (unless already changed)
            if ($image->getAnounce() === $this) {
                $image->setAnounce(null);
            }
        }

        return $this;
    }

    public function getIntro(): ?string
    {
        return $this->intro;
    }

    public function setIntro(string $intro): self
    {
        $this->intro = $intro;

        return $this;
    }

    /**
     * Get the value of imageName
     */
    public function getImageName()
    {
        return $this->imageName;
    }

    /**
     * Set the value of imageName
     */
    public function setImageName($imageName): self
    {
        $this->imageName = $imageName;

        return $this;
    }

    /**
     *@return File|null
     */
    public function getCoverImage(): ?File
    {
        return $this->coverImage;
    }

    /**
     *@param null|File
     *@return Anounce
     */
    public function setCoverImage(?File $coverImage): Anounce
    {
        $this->coverImage = $coverImage;
        if ($this->coverImage instanceof UploadedFile) {
            $this->createdAt = new \DateTime('now');
        }

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

}

src/Entity/Comment.php
<?php

namespace App\Entity;

use App\Repository\CommentRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=CommentRepository::class)
 */
class Comment
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $mail;

    /**
     * @ORM\Column(type="text")
     */
    private $content;

    /**
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Author;

    /**
     * @ORM\ManyToOne(targetEntity=Anounce::class, inversedBy="comments")
     * @ORM\JoinColumn(onDelete="CASCADE")
     */
    private $anounce;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getMail(): ?string
    {
        return $this->mail;
    }

    public function setMail(string $mail): self
    {
        $this->mail = $mail;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getAuthor(): ?string
    {
        return $this->Author;
    }

    public function setAuthor(string $Author): self
    {
        $this->Author = $Author;

        return $this;
    }

    public function getAnounce(): ?Anounce
    {
        return $this->anounce;
    }

    public function setAnounce(?Anounce $anounce): self
    {
        $this->anounce = $anounce;

        return $this;
    }
}

src/Form/AnounceType.php
<?php

namespace App\Form;

use App\Entity\Anounce;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;

class AnounceType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title', null, [
                'label' => 'Titre :'
            ])
            ->add('desription', TextareaType::class, [
                'label' => 'Description :'
            ])
            ->add('price', null, [
                'label' => 'Prix:'
            ])
            ->add('address', null, [
                'label' => 'Adresse :'
            ])
            ->add('rooms', null, [
                'label' => 'Nombre de Chambres :'
            ])
            ->add('isAvailable', null, [
                'label' => 'Disponibilité :',
            ])
            ->add('coverImage', FileType::class, [
                'label' => 'Image de couverture :',
                'required' => false
            ])
            ->add('intro', null, [
                'label' => 'Introduction:'
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Anounce::class,
        ]);
    }
}

src/Controller/AnounceController.php
<?php

namespace App\Controller;

use App\Entity\Anounce;
use App\Entity\Comment;
use App\Form\AnounceType;
use App\Form\CommentType;
use App\Repository\AnounceRepository;
use DateTime;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

#[Route('/anounce')]
class AnounceController extends AbstractController
{   
    public function __construct(AnounceRepository $repository, EntityManagerInterface $em)
    {
        $this->repository = $repository;
        $this->em = $em;
    }

    #[Route('/', name: 'anounce_index', methods: ['GET'])]
    public function index(): Response
    {   
        $anounces = $this->repository->findOrder();
        return $this->render('anounce/index.html.twig', [
            'anounces' => $anounces,
        ]);
    }

    #[Route('/{slug}', name: 'anounce_show')]
    public function show(Anounce $anounce, Request $request): Response
    {   
        $comment = new Comment();
        $commentform = $this->createForm(CommentType::class, $comment);
        $commentform->handleRequest($request);
        if ($commentform->isSubmitted() && $commentform->isValid()) {
            $comment->setCreatedAt(new DateTime());
            $anounce->addComment($comment);
            $this->em->persist($comment);
            $this->em->flush();
            $this->addFlash(type:'success', message:'Commentaire posté avec succés!');
            return $this->redirectToRoute('anounce_show', array('slug'=> $anounce->getSlug()));
        }
        return $this->render('anounce/show.html.twig', [
            'commentform' => $commentform->createView(),
            'anounce' => $anounce,
        ]);
    }

}

templates/anounce/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Anounce index{% endblock %}


{% block body %}

<h1 class="my-5">Toutes les annonces...</h1>
{% for message in app.flashes('success') %}
    <div class='alert alert-success'>{{message}}</div>
{% endfor %}

<div class="row">
    {% for anounce in anounces %}
    <div class="col-md-3 d-flex  align-items-stretch">
        <div class="card shadow-lg text-center mb-5 bg-body rounded">
            <div class="card-header">
                <strong> 
                {% if anounce.rooms < 2 %} 
                    Une Chambre 
                {% else %}
                    {{ anounce.rooms }} Chambres
                {% endif %}  à {{ anounce.price | number_format(0, ',', ' ')}}Fcfa <br> <small>{{ anounce.comments.count()}} commentaires </small></strong>
            </div> 
            <img style="width: 240px; height: 100px;" class="card-img-top" src="{{anounce.imageName}}" alt="{{anounce.imageName}}">
            <div class="card-body">
                <small style="font-size: 1rem; color:black;"class="card-title"> {{ anounce.title }}</small>
                <a class=" card-botom btn btn-primary" href=" {{path('anounce_show', {'slug': anounce.slug})}} "> Details </a>
            </div>
            <div class="card-footer">
                <small><i class="fas fa-map-marker-alt">{{ anounce.address }}</i></small>
                <br><small>Publié {{anounce.createdAt|ago(locale='fr')}}</small>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
<nav aria-label="Page navigation example">
  <ul class="pagination justify-content-center">
    <li class="page-item disabled">
      <a class="page-link" href="#" tabindex="-1">Previous</a>
    </li>
    <li class="page-item"><a class="page-link" href="#">1</a></li>
    <li class="page-item"><a class="page-link" href="#">2</a></li>
    <li class="page-item"><a class="page-link" href="#">3</a></li>
    <li class="page-item">
      <a class="page-link" href="#">Next</a>
    </li>
  </ul>
</nav>
{% if app.user %}
    <a href="{{ path('admin_anounce_new') }}" class="btn btn-primary">Nouvelle annonce</a>
{% endif %}

{% endblock %}

templates/anounce/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Anounce{% endblock %}

{% block stylesheets %}
    <style>
    #titre{
        padding: 80px;
        color: #fff;
        text-shadow: 5px 5px 10px gray;
        font-size: 2rem;
        background-color:rgba(41, 47, 41, 0.5);
        height: inherit;
        width: 1110px;
        height: 400px ;
        background-image: url({{anounce.coverImage}});    
    }
    </style>
    <link rel="stylesheet" href="/css/bootstrap.min.css">
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <link rel="stylesheet" href="/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="/css/style.css"/>
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>
    

{% endblock %}

{% block body %}
    <div class="shadow-lg">
        <div class="container" id="titre">
            <p style="font-size: 4rem; color: #fff;">{{anounce.title}}</p>
            <p> {{anounce.intro}} </p>
            <p>{{anounce.rooms}} Chambres à {{anounce.price}} Fcfa</p>
        </div>
    </div>
    <div class="row d.flex mt-3 jusify-content-around">
        <div class="col-md-8">
            <div class="container">
                <h3>Description:</h3>
                <p>{{anounce.desription | nl2br }}</p>
                <h3>Caractéristiques:</h3>
                <table class="table table-hover">
                    <tr class="table-default">
                        <td>Adresse:</td>
                        <td>{{anounce.address}}</td>
                    </tr>
                    <tr class="table-primary">
                        <td>Chambres:</td>
                        <td>{{anounce.rooms}}</td>
                    </tr>
                </table>
            </div>
            {% if anounce.comments.count() > 0 %}
            <div class="container">
                <h5>Commentaires :</h5>
                {% for comment in anounce.comments %}
                <div class="alert alert-dismissible alert-secondary shadow-sm p-3 mb-5 rounded">
                    <h5>{{comment.author}} a dit:</h5>
                    <p>"{{comment.content | nl2br}}"</p>
                </div>
                {% endfor %}
            </div>
            {% endif %}
        </div>
        <div class="col-md-4">
        {% set user = anounce.user %}
            <div class="container shadow-lg p-3 mb-5 rounded">
                <div class="row d-flex flex-column m-3">
                    <div>
                        <img class="img-thumbnail rounded-circle" src="https://picsum.photos/100/100" alt="">
                    </div>
                    <div>
                        <H3>{{user.name}} {{user.lastName}} </H3>
                        <h6>{{user.email}} </h6>
                        <h6>{{user.address}} </h6>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% for message in app.flashes('success') %}
        <div class='alert alert-success'>{{message}}</div>
    {% endfor %}
    <div class="row d.flex mt-3 ml-10 jusify-content-around">
        <div class="col-md-4">
            <h3>Commentez l'annonce</h3>
            {{form_start(commentform)}}
                {{form_row(commentform.Author, {attr: {class: 'form-control'} })}}
                {{form_row(commentform.mail, {attr: {class: 'form-control'} })}}
                {{form_row(commentform.content, {attr: {class: 'form-control'} })}}
                <button type="submit" class="btn btn-primary">Commenter</button>
            {{form_end(commentform)}}
        </div>
    </div>
    <br><br><br>
    

    <a href="{{ path('admin_anounce_index') }}" class="btn btn-success">Retour à la liste des annonces</a>

    {% if app.user %}
        <a href="{{ path('admin_anounce_edit', {'slug': anounce.slug}) }}" class="btn btn-primary">Modifier l'annonce</a>

    {{ include('admin/_delete_form.html.twig') }}
    {% endif %}
{% endblock %}